FROM mulesoft/flex-gateway:1.8.1

ENV FLEX_DYNAMIC_PORT_ENABLE=true \
  FLEX_DYNAMIC_PORT_ENVAR=PORT \
  FLEX_DYNAMIC_PORT_VALUE=8081 \
  FLEX_CONNECTION_IDLE_TIMEOUT_SECONDS=60 \
  FLEX_STREAM_IDLE_TIMEOUT_SECONDS=300 \
  FLEX_METRIC_ADDR=tcp://127.0.0.1:2000 \
  FLEX_SERVICE_ENVOY_DRAIN_TIME=30 \
  FLEX_SERVICE_ENVOY_CONCURRENCY=1

COPY rootfs/ /

USER root
RUN install -d -m 777 /usr/local/share/mulesoft/flex-gateway/conf.d/
USER 65532:0

ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["/init"]
