#!/usr/bin/with-contenv sh
# shellcheck shell=sh

logMessageDebug() {
  [ "$FLEX_LOG_LEVEL" -ge 8 ] && logMessage "[debug] $1" || true
}

logMessageInfo() {
  [ "$FLEX_LOG_LEVEL" -ge 4 ] && logMessage "[info] $1" || true
}

logMessageWarning() {
  [ "$FLEX_LOG_LEVEL" -ge 2 ] && logMessage "[warn] $1" || true
}

logMessageError() {
  [ "$FLEX_LOG_LEVEL" -ge 1 ] && logMessage "[error] $1" || true
}

logMessage() {
  echo "[$SERVICE]$1"
}

processTemplate()
{
  IN=$1
  DIR=$(dirname $IN)
  OUT=$(awk '/#@name/{print $2}' "$IN")
  OUT=${OUT:-$DIR/$(basename "$IN" .template)}

  logMessageInfo "Process Template $IN > $OUT"

eval "cat <<EOF
$(cat $IN | grep -v '^#@')
EOF
" > "$OUT"

}

process() {
  DIR=$1

  for file in $(find "${DIR}" -maxdepth 1 -type f -follow 2> /dev/null | sort); do
    KIND=$(awk '/#@kind/{print $2}' "$file")

    [ "$KIND" = "Template" ] && processTemplate "$file"
  done
}

SERVICE="cont-init.d/configure"
FLEX_LOG_LEVEL=${FLEX_LOG_LEVEL:-4}

process "/etc/mulesoft/flex-gateway/conf.d"

# exec "$@"
