#!/usr/bin/env bash
# shellcheck shell=bash

export FLEX_CONFIG_DIR="/etc/mulesoft/flex-gateway/conf.d:/usr/local/share/mulesoft/flex-gateway/conf.d:/var/tmp/mulesoft/flex-gateway/conf.d"
export FLEX_OUTPUT_CONFIG_DIR=/var/tmp/mulesoft/flex-gateway
export FLEX_SERVICE_ENVOY_BIN_PATH=/etc/mulesoft/flex-gateway/services/envoy
export FLEX_SERVICE_FLUENT_BIN_PATH=/etc/mulesoft/flex-gateway/services/fluent
export FLEX_SSL_TRUSTEDCA_FILENAME=/etc/ssl/certs/ca-certificates.crt

mkdir -p "${FLEX_OUTPUT_CONFIG_DIR}/conf.d" || exit 1

echo "${FLEX_REGISTRATION}" > /var/tmp/mulesoft/flex-gateway/conf.d/registration.yaml || exit 1

cp -r /etc/services.d "${FLEX_OUTPUT_CONFIG_DIR}/" || exit 1

exec /usr/bin/s6-svscan "${FLEX_OUTPUT_CONFIG_DIR}/services.d"
